services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build && npm start"
    networks:
      - NazarNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nazar-chat.rule=Host(`nazar-chat.aisouthside.com`)"
      - "traefik.http.routers.nazar-chat.entrypoints=websecure"
      - "traefik.http.routers.nazar-chat.tls=true"
      - "traefik.http.services.nazar-chat.loadbalancer.server.port=3000"

networks:
  NazarNet:
    external: true
