services:
  web:
    image: sponcino23/whatsapp-claude-meta:latest
    volumes:
      - whatsapp_data:/app/data
    environment:
      NODE_ENV: "production"
      META_VERIFY_TOKEN: "sdfhsdfh23562g34r"
    networks:
      - NazarNet
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whatsapp-claude.rule=Host(`nazar-chat.aisouthside.com`)"
        - "traefik.http.routers.whatsapp-claude.entrypoints=websecure"
        - "traefik.http.routers.whatsapp-claude.tls=true"
        - "traefik.http.routers.whatsapp-claude.tls.certresolver=letsencrypt"
        - "traefik.http.services.whatsapp-claude.loadbalancer.server.port=3000"

volumes:
  whatsapp_data:

networks:
  NazarNet:
    external: true
